language: python
python:
  - "3.6"
install:
 - "pip install -r requirements.txt"
 - "pip install python-coveralls"
script:
 coverage run --source="app/","tests/" -m unittest
after_success:
    - coveralls

