services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'create database flask_db;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
language: python
python:
  - "3.6"
install:
 - "pip install -r requirements.txt"
 - "pip install python-coveralls"
script:
 - nosetests  --with-coverage --cover-package=app
after_success:
    - coveralls

