services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
language: python
python:
  - "3.6"
install:
 - "pip install -r requirements.txt"
 - "pip install python-coveralls"
script:
 coverage run --source="app/","tests/" -m unittest
after_success:
    - coveralls

